### ISSUE TITLE
2023?

### ISSUE THREAD

**Issue by 6ghost9** [plumkewe/indie-app-santa#5]
Do you plan on making 2023 version of the list? Thanks for archiving BTW!

**Comment by plumkewe** [comment]
> Do you plan on making 2023 version of the list? Thanks for archiving BTW! 

Even better I've made a database! I can publish it even now but it has some odd naming. This repository is quite bad, it has a lot of typos. I created it when I knew little to no English.

![image](https://github.com/plumkewe/indie-app-santa/assets/113628928/e901579a-e2d7-465c-bbe5-2f072c61409a)

Thanks for asking.
